language: go

os: linux
dist: trusty
sudo: false

go:
  - "1.x"

script:
  - go fmt ./...
  - go vet ./...
  - go test -race ./...
  - ./testCoverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
